### ISSUE TITLE
Feature: new column (Use it to, It's like)

### ISSUE THREAD

**Issue by kpx-dev** [palsarma/aws_products#2]
Hi, 

I just found out about this repo, very helpful! I also saw this before:
https://www.expeditedssl.com/aws-in-plain-english

Would you be open to add those two new columns "Use it to" and "It's like" to these services? From the script, we maybe can add in new flag to generate this advanced report? 

If you are cool with this, I can help send in a PR. 

Thanks.

**Comment by palsarma** [comment]
@kpx-dev Thanks for your suggestion. If see that the website has not been kept up-to-date with the latest services. 
However, if you still want to add the two columns, please send in a PR. Thank you!!
